force-app/main/default/objects/Account/fields/ActivationDate__c.field-meta.xml
<CustomField>
    <fullName>ActivationDate__c</fullName>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ClinicSchemaName__c.field-meta.xml
<CustomField>
    <fullName>ClinicSchemaName__c</fullName>
    <label>Clinic Schema Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unique_Chewy_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_Chewy_ID__c</fullName>
    <externalId>true</externalId>
    <label>Unique Chewy ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Clinic.recordType-meta.xml
<RecordType>
    <fullName>Clinic</fullName>
    <active>false</active>
    <label>Clinic</label>
</RecordType>

force-app/main/default/objects/AccountActivation__c/AccountActivation__c.object-meta.xml
<CustomObject>
    <label>Account Activation</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Activations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountActivation__c/fields/JSON__c.field-meta.xml
<CustomField>
    <fullName>JSON__c</fullName>
    <label>JSON</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AccountActivation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clinic Activation</fullName>
            </value>
            <value>
                <fullName>Clinic Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountActivationJsonJob.cls
/*******************************************************************************************
* @Name           AccountActivationJsonJob
* @Author         Dominic Vario
* @Date           2022-05-25
* @Group          Schedulable
* @Description    Queries for all Clinics (Accounts) that went live in the past week, then prepares two separate JSON list objects to insert as Account Actication records.
MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
* 1.0              Dominic Vario      2022-05-25         Creation and initial deployment.
* 1.1              Dominic Vario      2022-05-25         Changed ClinicGoLiveDate__c to ActivationDate__c and set date range to TODAY.
*******************************************************************************************/

public class AccountActivationJsonJob implements Schedulable{
    public void execute(SchedulableContext sc) {
        Date today = System.today();
        List<Account> accountList = new List<Account>(); // Instantiate list to prevent null list exception
        accountList = [
            SELECT  ClinicSchemaName__c, Unique_Chewy_Id__c, PrimaryContact__r.FirstName, PrimaryContact__r.LastName, PrimaryContact__r.Email, ActivationDate__c
            FROM    Account
            WHERE   ActivationDate__c = :today
        ];
        if(!accountList.isEmpty()){
            List<Object> clinicActivationList = new List<Object>(); // test
            List<Object> clinicAdminList = new List<Object>();
            for(Account acc : accountList){
                // Clinic Activation Context
                clinicActivationList.add(JSON.serialize(
                    new Map<String,Object>{
                        'ClinicId' => acc.Unique_Chewy_Id__c
                        ,'ClinicSchemaName' => acc.ClinicSchemaName__c
                    }
                ));
                // Clinic Admin Context
                clinicAdminList.add(JSON.serialize(
                    new Map<String,Object>{
                        'ClinicSchemaName' => acc.ClinicSchemaName__c
                        ,'firstName' => acc.PrimaryContact__r.FirstName
                        ,'lastName' => acc.PrimaryContact__r.LastName
                        ,'email' => acc.PrimaryContact__r.Email
                    }
                ));
            }
            List<AccountActivation__c> accountActivationList = new List<AccountActivation__c>{
                (new AccountActivation__c( // Clinic Activation Context
                    JSON__c = '[' + clinicActivationList.toString().removeStart('(').removeEnd(')') + ']'
                    ,Type__c = 'Clinic Activation'
                    )
                ),(new AccountActivation__c( // Clinic Admin Context
                    JSON__c = '[' + clinicAdminList.toString().removeStart('(').removeEnd(')') + ']'
                    ,Type__c = 'Clinic Admin'
                    )
                )
            };
            if(!accountActivationList.isEmpty()){ // Checks to see if there are Account Activation records to insert
                Id cynthiaHearn = [
                        SELECT  Id 
                        FROM    User 
                        WHERE   FirstName = 'Cynthia'
                        AND     LastName = 'Hearn'
                        LIMIT   1
                    ].Id;
                try{
                    insert accountActivationList;
                    String chatterBody = 'Account Activation Job completed for date ' + String.valueOf(today) + '.';
                    FeedItem chatterPost = new FeedItem(  // Chatter Post to Cynthia Heard
                        ParentId = cynthiaHearn
                        ,Body = chatterBody
                    );
                    insert chatterPost;
                    if(Test.isRunningTest()){
                        throw new DmlException();
                    }
                }catch(Exception e){
                    Id ianVincent = [
                        SELECT  Id
                        FROM    User 
                        WHERE   FirstName = 'Ian'
                        AND     LastName = 'Vincent'
                        LIMIT   1
                    ].Id;
                    String chatterBody = 'Account Activation Job failed for date ' + String.valueOf(today) + '.';
                    List<FeedItem> chatterPosts = new List<FeedItem>{  // Chatter Post to Cynthia Heard
                        (new FeedItem(
                            ParentId = cynthiaHearn
                            ,Body = chatterBody
                            )
                        ),(new FeedItem(
                            ParentId = ianVincent
                            ,Body = chatterBody
                            )
                        )
                    };
                    insert chatterPosts;
                    System.debug('== ERROR MESSAGE == ' + e.getMessage());
                    System.debug('== ERROR CAUSE == ' + e.getCause());
                    System.debug('== ERROR LINE == ' + e.getLineNumber());
                }
            }
        }
    }
}