force-app/main/default/objects/Account/fields/SiteId__c.field-meta.xml
<CustomField>
    <fullName>SiteId__c</fullName>
    <defaultValue>&quot;MAIN PAY&quot;</defaultValue>
    <label>Site Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SupplierId__c.field-meta.xml
<CustomField>
    <fullName>SupplierId__c</fullName>
    <label>Supplier Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SupplierName__c.field-meta.xml
<CustomField>
    <fullName>SupplierName__c</fullName>
    <label>Supplier Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unique_Chewy_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_Chewy_ID__c</fullName>
    <externalId>true</externalId>
    <label>Unique Chewy ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GenerateCsvEmailErpInformationJobTest.cls
/*******************************************************************************************
* @Name             GenerateCsvEmailErpInformationJobTest
* @Author           Dominic Vario
* @Date             2022-08-04
* @Group            Test Class
* @Description      Tests the following class(es):
                    -- GenerateCsvEmailErpInformationJob -- Last Tested 2022-08-08 -- 95%
MODIFICATION LOG
* Version           Developer           Date                Description
*-------------------------------------------------------------------------------------------
* 1.0               Dominic Vario       2022-08-04          Initial development.
*******************************************************************************************/
@isTest
private class GenerateCsvEmailErpInformationJobTest {
    @TestSetup
    static void makeData(){
        List<Account> acctsToInsert = new List<Account>();
        for (Integer i = 0; i < 10; i++) {
            acctsToInsert.add(new Account(
                Name = 'Test Account ' + i
                ,Unique_Chewy_Id__c = String.valueOf(i)
                ,SupplierName__c = 'Supplier Name ' + String.valueOf(i)
                ,SupplierId__c = String.valueOf(i)
                ,SiteId__c = String.valueOf(i)
                ,OwnerId = UserInfo.getUserId()
            ));
        }
        insert acctsToInsert;
    }
    @IsTest
    static void testGenerateCSV(){        
        Test.startTest();
            System.assertEquals(0, Limits.getEmailInvocations(), 'No emails should be sent');
            //String cronExp = '0 0 0 * * ?';
            //Id jobId = System.schedule('Test GenerateCsvEmailErpInformationJob', cronExp, new GenerateCsvEmailErpInformationJob());
            GenerateCsvEmailErpInformationJob job = new GenerateCsvEmailErpInformationJob();
            job.execute(null);
            System.assertEquals(1, Limits.getEmailInvocations(), 'Email should be sent');
        Test.stopTest();        
    }
}